'use client'

import { motion } from 'motion/react'
import { SectionHeading } from '@/components/section-heading'
import { Reveal } from '@/components/reveal'

const linePoints = '20,172 113,145 206,107 299,64'
const heat = [0,1,0,1,2,1,2,0,2,2,3,2,2,3,1,3,3,3,2,3,4,3,4,3,4,4,4,4,4,4]

export function Progress() {
  return (
    <section id="results" className="border-y border-white/[0.06] bg-white/[0.018] py-24 md:py-32">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <SectionHeading eyebrow="Progress Made Visible" title="Understand What Is Working—and Repeat It" description="Simple, visual feedback makes progress easier to understand. Every chart below is illustrative example data, not a guaranteed result." />
        <div className="mt-14 grid gap-6 lg:grid-cols-2">
          <Reveal><article className="h-full rounded-3xl border border-white/[0.08] bg-black/60 p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.22em] text-[#d5ad53]">Weekly Alignment Score</p><h3 className="mt-2 font-display text-2xl font-semibold text-white">58 → 81 in four weeks</h3></div><span className="rounded-full border border-white/10 px-3 py-1 text-[.62rem] uppercase tracking-[.16em] text-white/35">Illustrative</span></div><svg viewBox="0 0 320 200" className="mt-7 w-full"><g stroke="rgba(255,255,255,.08)"><line x1="20" y1="40" x2="300" y2="40" /><line x1="20" y1="100" x2="300" y2="100" /><line x1="20" y1="160" x2="300" y2="160" /></g><motion.polyline points={linePoints} fill="none" stroke="#d5ad53" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" initial={{ pathLength: 0 }} whileInView={{ pathLength: 1 }} viewport={{ once: true }} transition={{ duration: 1.4 }} />{[[20,172,58],[113,145,64],[206,107,73],[299,64,81]].map(([x,y,v]) => <g key={v}><circle cx={x} cy={y} r="6" fill="#070707" stroke="#edcf78" strokeWidth="3" /><text x={x} y={y-14} textAnchor="middle" fill="rgba(255,255,255,.7)" fontSize="11">{v}</text></g>)}</svg><p className="mt-2 text-sm leading-6 text-white/45">The goal is not perfection. It is a visible pattern of stronger alignment and better follow-through.</p></article></Reveal>
          <Reveal delay={.06}><article className="h-full rounded-3xl border border-white/[0.08] bg-black/60 p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-[#d5ad53]">Daily Check-In Completion</p><h3 className="mt-2 font-display text-2xl font-semibold text-white">Consistency becomes visible</h3></div><span className="rounded-full border border-white/10 px-3 py-1 text-[.62rem] uppercase tracking-[.16em] text-white/35">30 days</span></div><div className="mt-9 grid grid-cols-10 gap-2">{heat.map((level, i) => <motion.div key={i} initial={{ opacity: 0, scale: .8 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: i * .015 }} className="aspect-square rounded-md border border-white/[0.06]" style={{ backgroundColor: `rgba(213,173,83,${.05 + level * .16})` }} />)}</div><div className="mt-8 flex items-center justify-between text-xs text-white/35"><span>Less consistent</span><span>More consistent</span></div><p className="mt-5 text-sm leading-6 text-white/45">A simple daily practice becomes easier to maintain when the system remembers, reflects, and follows up with you.</p></article></Reveal>
          <Reveal><article className="h-full rounded-3xl border border-white/[0.08] bg-black/60 p-6 sm:p-8"><p className="text-xs uppercase tracking-[.22em] text-[#d5ad53]">Decision Follow-Through</p><h3 className="mt-2 font-display text-2xl font-semibold text-white">See the accountability difference</h3><div className="mt-8 space-y-6">{[['Before AURA',42],['With Daily AURA Accountability',76]].map(([label, value]) => <div key={label as string}><div className="flex justify-between text-sm"><span className="text-white/55">{label}</span><span className="font-semibold text-white">{value}%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white/[0.07]"><motion.div initial={{ width: 0 }} whileInView={{ width: `${value}%` }} viewport={{ once: true }} transition={{ duration: 1 }} className="h-full rounded-full bg-[linear-gradient(90deg,#70450e,#e4c366)]" /></div></div>)}</div><p className="mt-8 rounded-xl border border-[#d5ad53]/15 bg-[#d5ad53]/[0.06] p-4 text-xs leading-5 text-white/45">Illustrative example—not a guaranteed result. Real aggregate data can replace this module as the program grows.</p></article></Reveal>
          <Reveal delay={.06}><article className="h-full rounded-3xl border border-white/[0.08] bg-black/60 p-6 sm:p-8"><p className="text-xs uppercase tracking-[.22em] text-[#d5ad53]">Personal Pattern Discovery</p><h3 className="mt-2 font-display text-2xl font-semibold text-white">Turn daily signals into useful insight</h3><div className="mt-7 space-y-4">{[['Higher sleep','Improved focus'],['Consistent check-ins','Stronger follow-through'],['Purpose alignment','Fewer reactive decisions']].map(([a,b],i) => <div key={a} className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><span className="text-sm text-white/55">{a}</span><span className="text-[#d5ad53]">→</span><span className="text-right text-sm font-semibold text-white/80">{b}</span></div>)}</div><p className="mt-7 text-sm leading-6 text-white/45">AURA Genesis™ helps you understand which choices support your best days—and which signals deserve attention earlier.</p></article></Reveal>
        </div>
      </div>
    </section>
  )
}
